source("../runCompare.R")
runCompare("resampleO")
runCompare("areaBasedALK")
runCompare("haulBasedALK")
runCompare("bootstrapDatras")
runCompare("stratifiedHLpseudoBootstrap")
runCompare("removeNandO")
